### ISSUE TITLE
Re: how or where to get the import library org.adempiere.model.* ?

### ISSUE THREAD

**Issue by dosindi** [adempiere/adempiere-gRPC-Server#11]
Kindly find the below screenshot error 
![image](https://user-images.githubusercontent.com/1564400/92399131-71e95f80-f132-11ea-9373-af3bdc398f94.png)

**Comment by yamelsenih** [comment]
Hi @dosindi add ADempiere source to project

**Comment by dosindi** [comment]
Hi @yamelsenih thank you for the response. How do you add the project to resolve these dependencies? Netbeans is the tool am using.

**Comment by yamelsenih** [comment]
Hi @dosindi please you should add adempiere library to project or use ti: https://hub.docker.com/repository/docker/erpya/adempiere-grpc-all-in-one
